version: '3.8'
services:
  user_profile_db:
    image: postgres:16.3-alpine
    container_name: user_profile_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - "user_profile_db:/var/lib/postgresql/data"
    networks:
      - taskboard-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  user-profile-service:
    container_name: user-profile-service
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Host=user_profile_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${DATASOURCE_PASSWORD}"
    depends_on:
      user_profile_db:
        condition: service_healthy
    ports:
      - "5103:8080"
    networks:
      - taskboard-net


volumes:
  user_profile_db:
    name: user_profile_db


networks:
  taskboard-net:
    external: true