version: '3.8'
services:
  user_profile_db:
    image: postgres:16.3-alpine
    container_name: user_profile_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - "user_profile_db:/var/lib/postgresql/data"
    networks:
      - user_profile_service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  user_profile_db:
    name: user_profile_db


networks:
  user_profile_service:
    external: false