version: '3.8'
services:
  organization_db:
    image: postgres:16.3-alpine
    container_name: organization_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - "organization_db:/var/lib/postgresql/data"
    networks:
      - taskboard-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  organization-service:
    container_name: organization-service
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Host=organization_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${DATASOURCE_PASSWORD}"
    depends_on:
      organization_db:
        condition: service_healthy
    ports:
      - "5104:8080"
    networks:
      - taskboard-net

volumes:
  organization_db:
    name: organization_db


networks:
  taskboard-net:
    external: true