version: '3.8'
services:
  card_db:
    image: postgres:16.3-alpine
    container_name: card_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - "card_db:/var/lib/postgresql/data"
    networks:
      - taskboard-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      
  card-service:
    container_name: card-service
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Host=card_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${DATASOURCE_PASSWORD}"
    depends_on:
      card_db:
        condition: service_healthy
    ports:
      - "5107:8080"
    networks:
      - taskboard-net


volumes:
  card_db:
    name: card_db


networks:
  taskboard-net:
    external: true