version: "3.8"

services:
  auth_db:
    image: postgres:16.3-alpine
    container_name: auth_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - "auth_db:/var/lib/postgresql/data"
    networks:
      - taskboard-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    container_name: auth-service
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Host=auth_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${DATASOURCE_PASSWORD}"
    depends_on:
      auth_db:
        condition: service_healthy
    ports:
      - "5101:8080"
    networks:
      - taskboard-net

volumes:
  auth_db:
    name: auth_db

networks:
  taskboard-net:
    external: true
