version: '3.8'
services:
  board_db:
    image: postgres:16.3-alpine
    container_name: board_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - "board_db:/var/lib/postgresql/data"
    networks:
      - taskboard-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
  hangfire_db:
    image: postgres:16.3-alpine
    container_name: hangfire_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5439:5432"
    volumes:
      - "hangfire_db:/var/lib/postgresql/data"
    networks:
      - taskboard-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  board-service:
    container_name: board-service
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Host=board_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${DATASOURCE_PASSWORD}"
      ConnectionStrings__Hangfire: "Host=hangfire_db;Port=5432;Database=hangfire_db;Username=${POSTGRES_USER};Password=${DATASOURCE_PASSWORD}"
    depends_on:
      board_db:
        condition: service_healthy
    ports:
      - "5106:8080"
    networks:
      - taskboard-net


volumes:
  board_db:
    name: board_db
  hangfire_db:
    name: hangfire_db


networks:
  taskboard-net:
    external: true